### ISSUE TITLE
More help 

### ISSUE THREAD

**Issue by Code-Slave** [kensand/rss-lemmy-bot#2]
Finally back at it.

So i setup again and set a time in compose
```
version: "3"
services:
  bot:
    image: kensand/rss-lemmy-bot:latest
    environment:
      - START_TIME="07/01/2023"
    volumes:
      - "./config.json:/rss-lemmy-bot/config.json"
```

```
  "feeds": [
    {
      "feedUrl": "https://newsadvance.com/search/?f=rss&t=article&c=news/community/nelson-county-times&l=50&s=start_time&sd=desc",
      "lemmyCommunities": [
        {
          "communityName": "centralva",
          "instanceUrl": "https://lemmy.mayes.io"
        }
      ],
      "schedule": {
        "minutes": 360
      }
    }
  ]
}
```

But it doesnt back populate:

Scanning feed https://newsadvance.com/search/?f=rss&t=article&c=news/community/nelson-county-times&l=50&s=start_time&sd=desc. Latest Item in feed is Sat Jul 01 2023 00:00:00 GMT+0000 (Coordinated Universal Time).

Finished scanning https://newsadvance.com/search/?f=rss&t=article&c=news/community/nelson-county-times&l=50&s=start_time&sd=desc. Posted 0 items. Latest item in feed is from Sun Jul 09 2023 10:15:00 GMT+0000 (Coordinated Universal Time).
